apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-infra-orchestrator.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ai-infra-orchestrator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ai-infra-orchestrator.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
